#!/bin/bash

source api

APP_STORE_NAME="LinStore"
APP_STORE_WIDTH=320
APP_STORE_HEIGHT=600

# generic stuff just in case an alternative yad instance exists, for some reason
YAD_COMMAND="yad"
YAD_FLAGS=""

ACCENT="green"

#pwd
if ! command -v "$YAD_COMMAND" &>/dev/null; then
    echo "YAD needs to be installed to run LinStore."
    exit 1
fi

if [ -f "gui" ] || [ -f "createapp" ] || [ -f "settings" ]; then
    cd .
else
    cd ~/.linstore
fi

if [[ $(xrandr --current) =~ "connected primary" ]]; then
    #echo "Dual monitor setup, placing on primary monitor"
    resolution=$(xrandr --current | grep " connected primary" | awk '{print $4}' | cut -d'+' -f1)
else
    #echo "Single monitor setup, no primary monitor"
    resolution=$(xrandr --current | grep " connected" | awk '{print $3}' | cut -d'+' -f1)
fi

horizontal=$(echo $resolution | cut -d'x' -f1)
vertical=$(echo $resolution | cut -d'x' -f2)
let "categoryPos=$horizontal/2-385"
let "categoryPosY=$vertical/2-320"

declare -A categories
declare -A category_apps

detect_and_write_architecture() {
    mkdir -p ~/.linstore
    case "$(uname -m)" in
    x86_64)
        echo "x64" >~/.linstore/architecture.txt
        ;;
    i686)
        echo "x86" >~/.linstore/architecture.txt
        ;;
    armv7l)
        echo "32" >~/.linstore/architecture.txt
        ;;
    aarch64)
        echo "64" >~/.linstore/architecture.txt
        ;;
    *)
        echo "Unknown architecture" >~/.linstore/architecture.txt
        ;;
    esac
}

if [ -e "etc/accent" ]; then
    ACCENT="$(cat etc/accent)"
    if [[ "$ACCENT" == "" ]]; then
        ACCENT="green"
    fi
fi
list_piapps() {
    piapps_file="etc/pi-apps-import"
    if [ -e "$piapps_file" ]; then
        cat "$piapps_file"
    else
        echo ""
    fi
}

theme_get() {
    website_file="etc/theme"
    if [ -e "$website_file" ]; then
        cat "$website_file"
    else
        echo ""
    fi
}
theme=$(theme_get)

###################################
# Graphical environments go below #

multi_install() {
    all_apps_list=()
    for app_dir in apps/*; do
        app_name=$(basename "$app_dir")
        if [ -e "$app_dir/install" ] || [ -e "$app_dir/install-$(cat ~/.linstore/architecture.txt)" ]; then
            app_icon="apps/$app_name/icon-24.png"
            all_apps_list+=("FALSE")
            all_apps_list+=("$app_icon")
            all_apps_list+=("$app_name")
        fi
    done

    APPS=$(GTK_THEME="${theme}" GDK_BACKEND=x11 $YAD_COMMAND --text "<big><b>Multi Installer</b></big>\nInstall multiple apps at once" --geometry=600x${APP_STORE_HEIGHT} --center --columns="3" \
        --list --checklist --image="images/logo/logo-64.png" --window-icon="images/logo/logo-64.png" --image-on-top --title "LinStore" --column="Select":chk --column "Icon:IMG" --column "Apps" \
        --button="Install"!images/button/install.png!:0 "${all_apps_list[@]}" --no-headers)
    response=$?
    ./api info "Response: $response"
    if [ $response -eq 0 ]; then
        if [[ "$APPS" != "" ]]; then
            list=""
            while IFS= read -r line; do
                list+="$(echo -e "$line" | awk -F "|" '{print $3}')"
                list+=$'\n'
            done <<< "$APPS"
            ./manage multi-install "$list"
        fi
    fi
}

app_details_page() {
    kill $(pgrep -f "title=App Details") > /dev/null 2>&1
    sleep 0.1
    pos=$(wmctrl -lG | grep "LinStore$" | awk '{print $3,$4}')
    x2=$((horizontal / 2 - 65))
    #y2=$((vertical / 2 - 300))

    TITLE="App Details"
    wmctrl -l | grep "$TITLE" | awk '{print $1}' | while read -r window_id; do
        wmctrl -ic "$window_id" > /dev/null 2>&1
    done

    local selected_app_name="${1//|/}"
    selected_app_name=$(echo "$selected_app_name" | sed 's/<[^>]*>//g')
    local app_directory="$(get_app_directory "$selected_app_name")"
    local app_icon="$app_directory/icon-64.png"
    local description=$(get_app_description "$selected_app_name")
    local creator=$(get_app_creator "$selected_app_name")
    local website=$(get_app_website "$selected_app_name")

    if [ -e "$HOME/.linstore/installscripts/$selected_app_name" ]; then
        installed="true"
    else
        installed="false"
    fi

    local install_command=$(./api install "$app_directory" "$selected_app_name")
    local uninstall_command=$(./api uninstall "$app_directory" "$selected_app_name")

    local open_command=$(./api open "$app_directory")
    buttons=()

    if [[ "$installed" == "true" ]]; then
        displayName="<b>${selected_app_name}</b> (<i>installed</i>)"
        buttonText="Uninstall"
        buttonImage="images/button/uninstall.png"
        # Create a temporary script for the commands
        temp_script=$(mktemp)
        echo "$uninstall_command && rm -rf \"$HOME/.linstore/installscripts/$selected_app_name\"" >"$temp_script"
        chmod +x "$temp_script"
        buttonCommand="bash -c 'bash $temp_script; rm $temp_script'"
        if [[ "$open_command" != "" ]]; then
            buttons+=("--button=<b>Open</b>!system-run:$open_command")
        fi
    else
        displayName="<b>${selected_app_name}</b> (<i>not installed</i>)"
        buttonText="<b>Install</b>"
        buttonImage="images/button/install.png"
        buttonCommand="$install_command"
    fi

    if [[ "$open" != "" ]]; then
        buttons+=("--button=Open!system-run:$open")
    fi

    if [[ -f "$app_directory/donate" ]]; then
        donate="Help out the developer by <a href='$(cat $app_directory/donate)'>donating</a>!\n"
    else
        donate=""
    fi

    (
        GDK_BACKEND=x11 $YAD_COMMAND --class LinStore --title="App Details" --geometry=450x${APP_STORE_HEIGHT}+${x2}+${categoryPosY} --form --class="LinStore" \
            --text "<big>${displayName}</big>\nBy <b>${creator}</b> (<a href='${website}'>App Website</a>)\n${donate}" \
            --field="<b>Description</b>:TXT" --no-edit "$description" --image="$app_icon" --window-icon="images/logo/logo-64.png" --image-on-top \
            --button="$buttonText!$buttonImage:$buttonCommand" "${buttons[@]}" --skip-taskbar --noclose &
    )

    rm -f /tmp/description.tmp
}

show_apps_in_category() {
    while true; do
        formatted_apps=()
        if [ "$1" == "All Apps" ]; then
            title="All Apps"
            while IFS= read -r line; do
                app_name=$(echo "$line" | awk -F'|' '{print $1}')
                app_dir="apps/$app_name"
                if [ -e "$app_dir/install" ] || [ -e "$app_dir/install-$(cat ~/.linstore/architecture.txt)" ] \
                || [ -e "$HOME/pi-apps/apps/$app_name/install-$(cat ~/.linstore/architecture.txt)" ] \
                || [ -e "$HOME/pi-apps/apps/$app_name/install" ]; then
                    app_icon="$(get_app_directory "$app_name")/icon-24.png"
                    formatted_apps+=("$app_icon")
                    if [ -e "$HOME/.linstore/installscripts/$app_name" ]; then
                        formatted_apps+=("<span fgcolor=\"$ACCENT\">$app_name</span>")
                    else
                        formatted_apps+=("$app_name")
                    fi
                fi
            done < "apps/app_categories"
        else
            title="Apps in $1 Category"
            #formatted_apps=()

            while IFS= read -r line; do
                [[ $(echo "$line" | awk -F'|' '{print $2}') == "$1" ]] || continue
                app=$(echo "$line" | awk -F'|' '{print $1}')
                if [ -e "apps/$app/install" ] || [ -e "apps/$app/install-$(cat ~/.linstore/architecture.txt)" ] \
                || [ -e "$HOME/pi-apps/apps/$app/install-$(cat ~/.linstore/architecture.txt)" ] \
                || [ -e "$HOME/pi-apps/apps/$app/install" ]; then
                    app_icon="$(get_app_directory "$app")/icon-24.png"
                    formatted_apps+=("$app_icon")
                    if [ -e "$HOME/.linstore/installscripts/$app" ]; then
                        formatted_apps+=("<span fgcolor=\"$ACCENT\">$app</span>")
                    else
                        formatted_apps+=("$app")
                    fi
                fi
            done < "apps/app_categories"
        fi

        GTK_THEME="${theme}" GDK_BACKEND=x11 $YAD_COMMAND --text "<big><b>$title</b></big>" --geometry=${APP_STORE_WIDTH}x${APP_STORE_HEIGHT}+${categoryPos}+${categoryPosY} --center --columns="2" \
                --list --image="images/logo/logo-64.png" --window-icon="images/logo/logo-64.png" --image-on-top --title "LinStore" --column "Icon:IMG" --column "Apps" --class="LinStore" \
                --button="Back"!images/button/back.png!:4 --separator="\n" --markup "${formatted_apps[@]}" --no-headers \
                --css="span{fgcolor:green;}" --select-action='bash -c "./gui showdetails \"%s\"" &'#> /dev/null 2>&1

        button_clicked=$?
        if [ $button_clicked -eq 4 ]; then
            show_app_store
            break
        fi

        show_app_store
        break
    done
}

show_app_store() {
    # Sort categories alphabetically and format with newlines
    sorted_categories=$(printf '%s\n' "$(get_categories)" | sort)

    list_items=()
    list_items=("images/categories/All Apps.png" "All Apps")
    while IFS= read -r category; do
        category_icon="images/categories/$category.png" # Path to category icons
        list_items+=("$category_icon")
        list_items+=("$category")
    done <<<"$sorted_categories"

    # Fetching a random line from the announcements file
    random_announcement=$(shuf -n 1 etc/announcements)

    # Search function

    selected_category_raw=$(GTK_THEME="${theme}" GDK_BACKEND=x11 $YAD_COMMAND --text "$random_announcement" \
        --geometry=${APP_STORE_WIDTH}x${APP_STORE_HEIGHT}+${categoryPos}+${categoryPosY} --center --columns="3" \
        "${list_items[@]}" --class="LinStore" \
        --list --image="images/logo/logo-64.png" --window-icon="images/logo/logo-64.png" --image-on-top --title "$APP_STORE_NAME" --column "Icon:IMG" \
        --column "Category" --button "!images/button/search.png"!"Search":"bash -c './api search' &" \
        --button "!images/button/update.png"!"Updates":"bash -c './update' &" --button "!images/button/settings.png"!"Settings":"bash -c './settings' &" \
        --no-headers --item-height="$welcome_height" --timeout=0 --no-close)
    exval=$?
    ./api info "Exit value: ${exval}"
    selected_category="${selected_category_raw//|/}"

    if [ "$exval" == "44" ]; then
        ./api search && show_app_store
    elif [ "$exval" -eq "143" ]; then
        pkill -f "yad*" > /dev/null 2>&1
    elif [ "$exval" -eq "252" ]; then
        pkill -f "yad*" > /dev/null 2>&1
    elif [ -n "$selected_category" ]; then
        show_apps_in_category "$selected_category" &
    fi
}

if [ ! -e apps/app_categories ]; then
        cache_categories "apps" "$(list_piapps)"
fi

if [[ $1 == "" ]]; then
    ./api logo
    ./api buildinfo
    echo ""
    use_piapps=$(list_piapps)
    ./api warning "Is LinStore able to use Pi-Apps' library? ${use_piapps}"
fi

if [[ $1 == "showdetails" ]]; then
    if [ -e /tmp/tmpname ]; then
        app_details_page "$(cat /tmp/tmpname && rm -r /tmp/tmpname)"
    else
        app_details_page "$(echo $2 | awk -F"'" '{print $4}')"
    fi
elif [[ $1 == "multi-install" ]]; then
    multi_install
else
    detect_and_write_architecture
    show_app_store
fi
