#!/bin/bash

echo """

██╗░░░░░██╗███╗░░██╗░██████╗████████╗░█████╗░██████╗░███████╗
██║░░░░░██║████╗░██║██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝
██║░░░░░██║██╔██╗██║╚█████╗░░░░██║░░░██║░░██║██████╔╝█████╗░░
██║░░░░░██║██║╚████║░╚═══██╗░░░██║░░░██║░░██║██╔══██╗██╔══╝░░
███████╗██║██║░╚███║██████╔╝░░░██║░░░╚█████╔╝██║░░██║███████╗
╚══════╝╚═╝╚═╝░░╚══╝╚═════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚══════╝"""
echo "Welcome to the LinStore installer!"
echo ""

if [ ! -e /usr/local/bin/install_package ]; then
    sudo echo
fi

# Check if git and yad are installed
missing_dependencies=false

error() {
    echo -e "\033[1;41m\033[97m ERROR:\033[0;41m $1 \033[0m" 1>&2
}
warning() {
    echo -e "\033[1;43m\033[97m WARNING:\033[0;43m $1 \033[0m" 1>&2
}
information() {
    echo -e "\033[1;104m\033[30m INFO:\033[0;104m $1 \033[0m" 1>&2
}

if ! command -v git &>/dev/null; then
    echo "Git is not installed. Please install Git and rerun the installation."
    missing_dependencies=true
fi

if ! command -v yad &>/dev/null; then
    warning "Various dependencies required for LinStore are not installed."
    read -rp "Do you want to install them? (Y/N): " choice
    if [[ $choice =~ ^[Yy]$ ]]; then
        information "Installing dependencies..."
        sudo apt update > /dev/null 2>&1
        sudo apt install yad wmctrl imagemagick -y > /dev/null 2>&1
    else
        error "Cannot continue, exiting."
        missing_dependencies=true
    fi
fi

if [ "$missing_dependencies" = true ]; then
    exit 1
fi

temp_dir=$(mktemp -d) || {
    error "Failed to create a temporary directory, exiting."
    exit 1
}

if [ -d "$HOME/.linstore/tmp" ]; then
    information "Using existing cloned files from update..."
    mv "$HOME/.linstore/tmp" "$temp_dir"
    rm -rf "$HOME/.linstore/tmp"
else
    information "Cloning necessary files from the repository..."
    if ! git clone https://github.com/techguy16/linstore "$temp_dir" > /dev/null 2>&1; then
        error "Failed to clone repository. Exiting installation."
        rm -rf "$temp_dir"
        exit 1
    fi
fi

information "Copying files to the installation directory..."
install_dir="$HOME/.linstore"
mkdir -p "$install_dir"
cp -r "$temp_dir"/* "$install_dir"
cd "$install_dir"
chmod +x *
rm -rf "$temp_dir"  # Clean up temporary directory

# Create a bin directory if it doesn't exist

if [ ! -e /usr/local/bin/install_package ]; then
    sudo mkdir -p /usr/local/bin
    # Copy files to /usr/local/bin
    information "Copying executable files to /usr/local/bin..."
    sudo cp "$install_dir"/tools/*_package /usr/local/bin/
fi

# Create a desktop shortcut for GUI
desktop_file="$HOME/.local/share/applications/LinStore.desktop"
information "Creating desktop shortcut..."
cat <<EOF >"$desktop_file"
[Desktop Entry]
Name=LinStore
Comment=The lightest and fastest Linux app store.
Exec=$HOME/.linstore/gui
Type=Application
Version=1.0
Terminal=false
StartupWMClass=LinStore
Icon=$HOME/.linstore/images/logo/logo.png
Categories=Utility;System;PackageManager;
EOF

information "Cleaning up cached files..."
rm -rf "$HOME/.linstore/tmp/"

information "LinStore installed successfully!"
