#!/bin/bash

APP_STORE_DIRECTORY="apps"
CATEGORIES_FILE="etc/categories"
THEMES_DIRECTORY="/usr/share/themes"
THEMES_FILE="etc/theme"

show_settings() {
    pkill -f "yad.*"
    
    selectedtheme=$(cat "etc/theme" 2>/dev/null)
    if [[ ! -f "etc/theme" ]]; then
        ./api error "etc/theme does not exist"
    fi
    #echo "$selectedtheme"
    if [[ -z "$selectedtheme" || "$selectedtheme" == " " ]]; then
        themes=("System Default")
    else
        themes=("${selectedtheme} (currently selected)!System Default")
    fi
    
    while IFS= read -r -d '' theme; do
        # Extract just the name of the theme directory from its full path
        theme_name=$(basename "$theme")
        themes+=("$theme_name")
    done < <(find "$THEMES_DIRECTORY" -maxdepth 1 -mindepth 1 -type d -print0 | sort -z)
    theme_string=""
    for theme in "${themes[@]}"; do
        if [ -n "$theme_string" ]; then
            theme_string+="!"
        fi
        theme_string+="$theme"
    done
    
    selectededitor=$(cat "etc/editor" 2>/dev/null | sed -r 's/ \(currently selected\)//g')
    #echo "$selectededitor"
    if [[ ! -f "./etc/editor" ]]; then
        ./api error "etc/editor does not exist"
    fi
    if [[ -z "$selectededitor" || "$selectededitor" == " " ]]; then
        texteditors="System Default"
    else
        texteditors="${selectededitor} (currently selected)!System Default"
    fi
    texteditors+="!Visual Studio Code!Geany!Gedit!Mousepad!VSCodium"

    import_piapps_file=$(cat "etc/pi-apps-import" 2>/dev/null)
    if [[ ! -f "./etc/pi-apps-import" ]]; then
        ./api error "etc/pi-apps-import does not exist"
    fi
    #echo "$selectededitor"
    if [[ -z "$import_piapps_file" || "$import_piapps_file" == " " ]]; then
        import_piapps="FALSE"
    else
        import_piapps="${import_piapps_file}"
    fi

    express_updates_file=$(cat "etc/express-updates" 2>/dev/null)
    if [[ ! -f "./etc/express-updates" ]]; then
        ./api error "etc/express-updates does not exist"
    fi
    #echo "$selectededitor"
    if [[ -z "$express_updates_file" || "$express_updates_file" == " " ]]; then
        express_updates="FALSE"
    else
        express_updates="${express_updates_file}"
    fi
    
    # I don't know why these are around this way, and why they only work that way.
    settings=$(yad --form \
        --title="Settings" --columns=1 --output-by-row \
        --width="150" --height="400" --center --borders=20 \
        --field="<big><b>LinStore Settings</b></big>":LBL "" \
        --field="<b>Theme</b>":CB "$theme_string" \
        --field="<b>Text Editor</b>":CB "$texteditors" \
        --field="Show apps from Pi-Apps (if installed)":CHK "${import_piapps}" \
        --field="Express Updates":CHK "${express_updates}" \
        --field=":LBL" "" \
        --field="<big><b>App Management</b></big>":LBL "" \
        --field="<b>Create App</b>"!document-new!"Create an app for LinStore and Pi-Apps!":FBTN "./createapp create" \
        --field="<b>Import App</b>"!document-open!"Import an app not available in the repository":FBTN "./createapp import" \
        --button="<b>OK</b>!gtk-ok":0 \
        --button="<b>Cancel</b>!gtk-cancel":1)
    
    # Extracting the selected text editor value from settings
    
    yad_ret=$?
    
    if [[ $yad_ret -eq 0 ]]; then
        echo "$settings"
        fixed_settings=$(echo "$settings" | sed -r 's/ \(currently selected\)//g')
        echo "$fixed_settings"
        
        selected_text_editor=$(echo "$fixed_settings" | awk -F '|' '{print $3}')
        echo "$selected_text_editor"
        # Echoing to the 'etc/editor' file based on the selected text editor
        case "$selected_text_editor" in
            "System Default") echo "xdg-open" >"etc/editor" ;;
            "Visual Studio Code") echo "code" >"etc/editor" ;;
            "Geany") echo "geany" >"etc/editor" ;;
            "Gedit") echo "gedit" >"etc/editor" ;;
            "Mousepad") echo "mousepad" >"etc/editor" ;;
            "VSCodium") echo "codium" >"etc/editor" ;;
            *) echo "$selected_text_editor" >"etc/editor" ;;
        esac

        selected_theme=$(echo "$fixed_settings" | awk -F '|' '{print $2}')
        echo $selected_theme
        if [[ "$selected_theme" == "System Default" ]]; then
            echo "yes"
            selected_theme_path=""
            echo "$selected_theme_path" >"$THEMES_FILE"
        else
            selected_theme_path=$(find "$THEMES_DIRECTORY" -maxdepth 1 -mindepth 1 -type d -name "$selected_theme" -exec basename {} \; -quit)
            echo "$selected_theme_path" >"$THEMES_FILE"
        fi

        import_from_piapps=$(echo "$fixed_settings" | awk -F '|' '{print $4}')
        echo $import_from_piapps > "etc/pi-apps-import"

        express_updates=$(echo "$fixed_settings" | awk -F '|' '{print $5}')
        echo $express_updates > "etc/express-updates"
        
        ./gui
    elif [[ $yad_ret -eq 252 ]]; then
        ./gui
    elif [[ $yad_ret -eq 1 ]]; then
        ./gui
    fi
}

show_settings > /dev/null
#show_settings
