name: App Submission
title: EDIT ME! Include the app name.
description: Submit an app to be added to LinStore.
labels: ["App Submission"]
body:
  - type: input
    id: app-name
    attributes:
      label: What is the app's name?
      placeholder: i.e Firefox, Visual Studio Code
    validations:
      required: true
      
  - type: textarea
    id: host
    attributes:
      label: (Optional) Where is the app's Git repository?
      placeholder: i.e GitHub or Gitlab repository
    validations:
      required: false
  
  - type: textarea
    id: about
    attributes:
      label: App info
      description: What is the purpose of the app?
      placeholder: What does the app do?
    validations:
      required: true
      
  - type: textarea
    id: zip
    attributes:
      label: Upload ZIP file
      description: "Upload your zip file for this app, or if you have any other relevant files, upload or link them here."
      placeholder: "Tips: You can upload files here by clicking to expand the regular text-box"
    validations:
      required: false
      
  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      description: All of the following MUST be met BEFORE the app can be included.
      options:
        - label: I have confirmed that this app is legal and not piracy.
          required: true
        - label: I have confirmed I have created the app or I have permission from the app owner to distribute the app.
          required: true
        - label: I have confirmed that this app has never been suggested in https://github.com/techguy16/LinStore/issues and https://github.com/techguy16/LinStore/pulls, and it is not already in LinStore.
          required: true