#!/bin/bash
VERSION="2861b4e99f492f5bbbd02f0a8a2d2b663dfe90cf"

mkdir -p "$HOME/.techguy16"

rm -rf "$HOME/.techguy16/LinuxPatcher"
git clone https://github.com/techguy16/LinuxPatcher "$HOME/.techguy16/LinuxPatcher"

chmod +x "$HOME/.techguy16/LinuxPatcher/gui"

cat <<EOF >"$HOME/.local/share/applications/LinuxPatcher.desktop"
[Desktop Entry]
Name=LinuxPatcher
Comment=Patch annoyances in Linux
Exec=$HOME/.techguy16/LinuxPatcher/gui
Type=Application
Version=1.0
Terminal=false
Categories=Utility;System;
EOF