#!/bin/bash

sudo apt install curl lsb-release ca-certificates -y
if [[ "$(cat /proc/device-tree/model)" == "Raspberry Pi"* ]]; then
    sudo echo "psi=1" >> /boot/firmware/cmdline.txt
fi

# Modified from https://github.com/waydroid/waydroid/issues/214#issuecomment-1120926304
sudo apt install build-essential cdbs devscripts equivs fakeroot \
  git git-buildpackage git-lfs libgbinder-dev -y

sudo wget https://raw.githubusercontent.com/MrCyjaneK/waydroid-build/main/build_changelog \
  -O /usr/bin/build_changelog
sudo chmod +x /usr/bin/build_changelog

mkdir /tmp/gbinder
cd /tmp/gbinder
git clone https://github.com/waydroid/gbinder-python.git
cd gbinder-python
build_changelog
sudo mk-build-deps -ir -t "apt -o Debug::pkgProblemResolver=yes -y --no-install-recommends"
sudo debuild -b -uc -us
sudo apt install -f -y ../*.deb
sudo rm -rf /usr/bin/build_changelog
########################################################################################

sudo curl -Sf https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/waydroid.list

sudo apt update
sudo apt install waydroid -y

sudo waydroid init -f -s GAPPS # Install with G-Apps support