#!/bin/bash

sudo apt install curl ca-certificates -y
curl -s https://repo.waydro.id | sudo bash

# Modified from https://github.com/waydroid/waydroid/issues/214#issuecomment-1120926304
sudo apt install build-essential cdbs devscripts equivs fakeroot \
  git git-buildpackage git-lfs libgbinder-dev -y

sudo wget https://raw.githubusercontent.com/MrCyjaneK/waydroid-build/main/build_changelog \
  -O /usr/bin/build_changelog
sudo chmod +x /usr/bin/build_changelog

mkdir /tmp/gbinder
cd /tmp/gbinder
git clone https://github.com/waydroid/gbinder-python.git
cd gbinder-python
build_changelog
sudo mk-build-deps -ir -t "apt -o Debug::pkgProblemResolver=yes -y --no-install-recommends"
sudo debuild -b -uc -us
sudo apt install -f -y ../*.deb
sudo rm -rf /usr/bin/build_changelog
########################################################################################

sudo apt install waydroid -y

sudo waydroid init -f -s GAPPS # Install with G-Apps support