name: Update apps

on:
  schedule:
    - cron: '40 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run update checker
      run: |
        bash tools/updates.sh

    - name: Commit changes
      run: |
        current_date=$(date +'%d/%m/%Y, %H:%M')
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "Update $(cat updates_list.txt)"
      
    - name: Push changes
      run: |
        git push https://${{ secrets.GH_TOKEN }}@github.com/techguy16/LinStore.git